- python-api/.gitignore
This is user-specific and shouldn't be in version control.
> Ignore log_system_information.txt

- autostart/startupdemo
- startupdemo.py
/autostart/ contains a bash script that kicks off startupdemo.py. The rasbian image is configured to automatically run the bash script in /autostart/, so this should allow us to configure the autostart experience via github without reflashing everything.
> Adding autostart functionality

- test.py
> Using 1097 board defaults in test.py

- test.py
This pr contains:
- max fps limitation for streams
- fix for occasional crashes
> Implement max fps limitation and improve firmware stability

- .gitmodules
- README.md
This loads the `depthai-api` Git repo as a submodule.
The `depthai-api` repo contains the host-side code that is used to build the Python `.so` file. End users do not need to grab this submodule unless they are building the `so` file from source.
Instructions for building the `so` file will be within the `depthai-api` repo README.
Run the following to grab the submodule:
```
git submodule update --init
```
> Load depthai-api repo as a submodule

- calibrate.py
- calibrate_and_test.py
Usage: python3 calibrate_and_test.py
Functionality: On succesful calibration, depth stream is automatically opened for quality verification.
> add script to run depth stream after succesful calibration

- calibrate.py
- calibrate_and_test.py
- depthai_helpers/calibration_utils.py
Fix calibrate_and_test script after merge
> Calibration fix

- calibrate.py
I noticed some things I didn't like on PR #66 
And instead of proposing a new solution, I just wrote one quick, easier for me to operate on a real code instead of suggestions
Key issues I found or changes I made
- first, you check metadata on `packet_list[-2]` and `packet_list[-1]` (last frames in array), whereas to `packet_pair` you take `packet_list[0]` and `packet_list[1]`
- There is an assumption that the last two items in `packet_list` are most recent ones
- There may be a case that the `packet_pair` will consist of two left camera frames (we just assume they won't come so fast to pass the timestamp check)
Also, creating two arrays (`packet_list` and `packet_pair`), just to get two most recent left and right frames, was something I'd like to avoid - I always tend to stick to …
> propose another aproach to timestamp measurements

- README.md
- depthai.py
- requirements.txt
So far this PR does the following:
* Implements helper functions to draw nice labels and bounding boxes.
* Implements new display for mobilenet labeled objects which uses the aforementioned helper functions, it looks like this:
* Add note about needing to use --clean on build commands after updates.
* Improves clarity of a few code comments
* Adds a python requirements file
* Resizes and repositions the FPS counter
> UI/UX Improvements in visuals and dev cycle

- README.md
- depthai.py
- requirements.txt
Reverts luxonis/depthai#95
This does not work with `-bb` on `depth_sipp`:
`python3 test.py -s metaout previewout depth_sipp,5 -bb`
So just reverting for now until we get it compatible there.
> Revert "UI/UX Improvements in visuals and dev cycle"

- README.md
- requirements.txt
This MR adds back in some instructions for rebuilding the module and implements requirements.txt.
> Bring back requirements and readme updates from #95.

- calibrate.py
Show synchronized left and right captured frames in a single window
> Show synchronized left and right captured frames in a single window

- depthai.py
- depthai_helpers/cli_utils.py
- tests/test_cli_utils.py
This pull request changes and adds no functionality. It is purely to improve organization of code by breaking out like functions into a separate module. It also introduces some simple tests to be expanded on as the project grows. I do not have hardware on hand to test that the system runs as expected, but outputs to each function should remain the same and is tested.
Happy to update or add additional testing coverage.
> Add cli utils

- depthai.py
Example usage is shown in depthai.py
Press key: 
- 'f' to trigger autofocus
- '1' to change autofocus mode to auto
- '2' to change autofocus mode to continuous video
Other autofocus modes are also available (check depthai.AutofocusMode.__members__) but not yet tested.
> Trigger autofocus and change mode feature

- depthai.py
- depthai_helpers/cli_utils.py
Adjust the trackbar on the applicable frame (`depth_color_h, depth_sipp, disparity`) to adjust disparity confidence threshold.
Alternatively there are : 
`"-dct", "--disparity_confidence_threshold"` options, to set the default.
> Add trackbar for dynamically configurable disparity confidence threshold

- depthai.py
fix error when previewout is not enabled : -s metaout depth_sipp
> Fix error when previewout is not enabled : -s metaout depth_sipp

- depthai_demo.py
- depthai_helpers/arg_manager.py
- requirements.txt
This PR adds 'raw_color' stream for retrieving raw YUV420p frames of color camera
> Added stream for retrieving raw color frames

- calibrate_and_test.py
- depthai_demo.py
- depthai_helpers/arg_manager.py
- integration_test.py
- requirements.txt
- testsFunctional/runFunctionalTests.py
Stream `depth_raw` has been renamed to `depth` to match naming convention with other streams.
> Rename depth_raw to depth

- requirements.txt
Should fix issue https://github.com/luxonis/depthai/issues/226
Source-code PR: https://github.com/luxonis/depthai-python/pull/55
> Fix a scaling issue or crash with NN on rectified frames

- depthai_helpers/age_gender_recognition_handler.py
- depthai_helpers/config_manager.py
- depthai_helpers/mobilenet_ssd_handler.py
- requirements.txt
Related PR: https://github.com/luxonis/depthai-python/pull/57
Confidence threshold specified in JSON was not used in mobilenet decoding, so the results were filtered on host .. Also removed `depth_confidence_threshold` since there is no reason to have both for decoding and depth.
> Fix confidence threshold for mobilenet

- requirements.txt
Added sanity checks for common problems reported by @VanDavv 
Related PR:
https://github.com/luxonis/depthai-python/pull/59
> Output format checks

- requirements.txt
Source code PR: https://github.com/luxonis/depthai-python/pull/61
Should fix issue #244
> Fix X,Y,Z calc on NN bounding box

- requirements.txt
Revert from `0.11.1` to `0.10.0.0`
> Open3d version revert

- requirements.txt
... after merging https://github.com/luxonis/depthai-python/pull/56
Production support: 
- USB info (speed, SN)
- connected cams info
- write EEPROM at runtime
- fix crash with calib data zero
> Update to using latest python wheels

- model_compiler/model_compiler.py
Fixes #306 
Contains fixes from : #272
> Fix error when there is space in path

- depthai_helpers/arg_manager.py
Add all stream choices to help for -s
Remove newlines that were not rendered
> Remove deprecated stream from help

- depthai_helpers/arg_manager.py
> Revert "Remove deprecated stream from help"

- .gitignore
- depthai_helpers/version_check.py
- install_requirements.py
- requirements.txt
The wheel is built on my pi zero, and downloaded from google drive.
Tested on clean Raspberry OS (latest) following the docs (same as any other raspberry)
`sudo curl -fL http://docs.luxonis.com/_static/install_dependencies.sh | bash`
`git clone https://github.com/luxonis/depthai.git`
`python3 install_requirements.py`
`python3 depthai_demo.py -rgbf 5`
Fixes #324
> Add custom wheel for armv6 (pi zero) + aarch64 (jetson)

- .gitignore
- depthai_demo.py
- install_requirements.py
- requirements.txt
Removed error print for optional requirements.
Updated library for 1.0.0.0
> Release 1.0.0.0

- gen2_demo.py
added spatial option (-d) that displays coordinates of a detected object
> added spatial option (-d)

- depthai_demo.py
- depthai_helpers/arg_manager.py
- depthai_helpers/config_manager.py
This PR improves the code structure making it more flexible, also reorganizes where certain logic is kept in the code.
Contains also various runtime fixes to make the script more usable and stable
> Gen2 code refactor + improvements

- depthai_demo.py
- depthai_helpers/arg_manager.py
This PR allows to set the minumum and maximum depth thresholds, used by `setDepthLowerThreshold` and `setDepthUpperThreshold` methods respectively
> add --min_depth and --max_depth flags

- depthai_demo.py
- depthai_helpers/arg_manager.py
- depthai_helpers/config_manager.py
This PR is in progress.
Currently, it works to be used at most with these streams:
```
python depthai_demo.py -s color left right rectified_left rectified_right depth
```
Run preview shown here
TODO:
- Check if rectified images are correct
- Enable disparity and disparity_color show params
> add -s --show parameter

- depthai_demo.py
Changed branch to Main. Refer - https://github.com/luxonis/depthai/pull/358
> depthai_demo UI and visualisation improvements. Ref #358

- README.md
- depthai_demo.py
- depthai_helpers/arg_manager.py
- depthai_helpers/config_manager.py
- requirements-optional.txt
- requirements.txt
This PR allows users to pass YouTube video link on which DepthAI should download and run inference on.
Usage example
```
depthai_demo.py -vid https://www.youtube.com/watch?v=Y1jTEyb3wiI
```
resolves #373
> Modify -vid parameter to support inference on YouTube videos

- depthai_demo.py
- depthai_helpers/arg_manager.py
- depthai_helpers/config_manager.py
With this PR, users will be able to use `--openvino_version` flag to specify OpenVINO version used in pipeline.
Additionally, users are now able to run depthai_demo with custom blob, without blobconverter
> Add support for precompiled blob file and custom OpenVINO version

- depthai_demo.py
- tests/test_executor.py
> Fix meta_d2h test in Gen1

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Added issue template for a feature request.
Should we have any other title, like `[ENHANCEMENT]`?
> Added issue template for feature request

- depthai_demo.py
- depthai_helpers/config_manager.py
- depthai_helpers/utils.py
- resources/nn/openpose2/handler.py
- resources/nn/openpose2/openpose2.json
With this PR, the download issue from #397 will be resolved
The download failed on `main` due to the following error:
```
The support of IR v5 has been removed from the product. Please, convert the original model using the Model Optimizer which comes with this version of the OpenVINO to generate supported IR version
```
We should update the openpose IR files, but I decided to add an ability to specify a custom version in the model config file and utilize our blobconverter's mechanism to download a blob in a specific OpenVINO version.
This way, this model is now downloaded by default using OpenVINO 2020.4.
> Add openvino_version to model config & add openpose2 handler

- depthai_demo.py
With this PR, each label will have assigned a different color with which it will be drawn on the preview windows
> Show different colors per detected label

- depthai_demo.py
- depthai_helpers/arg_manager.py
- depthai_helpers/config_manager.py
`python3.6 depthai_demo.py --count 5`
`python3.6 depthai_demo.py --count tvmonitor`
I'm using bottles as an example because the model detects them accurately. 
Any ideas on how to get multiples of the object? So it would display eg. `2 people` instead of `2 person`
> Added object counting feature

- calibrate.py
Set min allowed square size for calibration to be greater than 2.2 cm.
> Added min allowed SquareSize

- requirements.txt
Update to `depthai` release `2.7.0.0` with POE (Ethernet) boards support
> Add POE boards support

- depthai_demo.py
- depthai_helpers/managers.py
- resources/nn/deeplabv3p_person/handler.py
This PR:
- Fixes deeplab handler, crashed when frames were received but no NN results were yet available
- Adds FPS report after demo script run (helped with https://github.com/luxonis/depthai-docs-website/pull/231)
> Minor demo tweaks

- requirements.txt
To make `yolo-v3` work on depthai-demo
> Updated version of depthai library to 2.8

- depthai_demo.py
- depthai_helpers/arg_manager.py
> Revert "Increase sigma range and default value"

- depthai_helpers/managers.py
This PR fixes the` disparity_color` mouse tracker display. With PoE devices, it showed `None` instead of the correct pixel value.
Main issue here was that the mouse tracker mechanism took values from MJPEG encoded frame, but I also cleaned up the code related to mouse tracking a bit.
> Fix mouse tracker on disparity stream over PoE

- depthai_demo.py
- depthai_helpers/arg_manager.py
- depthai_helpers/config_manager.py
This PR introduces shaves calculation method based on current cli params
> Calculate optimal number of shaves based on cli params

- depthai_helpers/managers.py
- requirements.txt
Updated the code to use version 2.9.0.0
> updated code to use version 2.9.0.0

- resources/nn/openpose2/handler.py
This PR adds a better handling for full FOV when running `openpose2` network
> Handle full FOV in openpose2 handler

- README.md
This PR updates README.md, changing flags to meet the current, camelCase ones
> Update README.md usage

- depthai_sdk/src/depthai_sdk/managers/blob_manager.py
- resources/nn/custom_model/custom_model.json
- tests/guided_manual_test.py
This PR fixes `$ python3 depthai_demo.py -cnn custom_model` and adds a test to this case to `guided_manual_tests.py` to make sure it works in future too
> Fix custom model .blob resolution

- depthai_sdk/setup.py
- depthai_sdk/src/depthai_sdk/managers/nnet_manager.py
This PR bumps SDK version and adds one fix. After this PR is merged, I will make a new SDK release, including changes introduced in #513
> Bump SDK version to 1.1.3

- callbacks.py
- depthai_demo.py
With this PR, using callbacks file will work again (`-cb / --callback`)
> Fix callbacks file parsing

- depthai_sdk/docs/source/index.rst
Added the image blow to the index docs page, with minor changes to the docs
> Removed top comment

- launcher/launcher.py
Adds capability to force checkout new version even if there were changes in the depthai repository
> Added capability to force update to a new version

- depthai_demo.py
Workaround for the crash on https://github.com/luxonis/depthai/issues/541
> Apply Qt6 GUI workaround also for macOS

- depthai_helpers/version_check.py
- requirements.txt
Solves https://github.com/luxonis/depthai/issues/553
> Update depthai lib to latest develop

- requirements.txt
Release notes: https://github.com/luxonis/depthai-python/releases/tag/v2.13.3.0
> Update to latest depthai: 2.13.3.0

- depthai_demo.py
- depthai_sdk/src/depthai_sdk/managers/nnet_manager.py
This PR fixes the issue with mirrored NN results, as the rectified streams are now mirrored on device
> Remove rectified streams detections mirroring

- depthai_demo.py
- depthai_sdk/requirements.txt
- depthai_sdk/src/depthai_sdk/managers/blob_manager.py
- depthai_sdk/src/depthai_sdk/utils.py
- gui/main.py
This PR introduces download progress indicator to Qt GUI, as shown in the demo below
Related blobconverter PR - https://github.com/luxonis/blobconverter/pull/31 - and release - https://github.com/luxonis/blobconverter/releases/tag/v1.2.8
> Add download progress indicator in Qt GUI

- depthai_demo.py
- log_system_information.py
- requirements-optional.txt
This PR adds sentry integration allowing us to capture runtime errors from our users
> Add sentry integration

- depthai_demo.py
- depthai_helpers/app_manager.py
- gui/main.py
- gui/views/MiscProperties.qml
- gui/views/root.qml
This PR introduces the ability to run Demo Apps from Qt GUI and then terminate them when we're done playing with the app
Usage demo
https://user-images.githubusercontent.com/5244214/147253793-23820ed0-4fdb-4ecb-8217-818239535e15.mov
> Add ability to run apps from GUI

- depthai_demo.py
This PR adds handles for KeyboardInterrup errors, exiting the program gracefully now
> Add keyboard interrupt catch blocks

- apps/uvc/main.py
- apps/uvc/requirements.txt
- depthai_helpers/app_manager.py
Using depthai from `gen2_uvc` branches on depthai-python and depthai-core.
Source code fix for XLink: https://github.com/luxonis/XLink/commit/48e760372739efba82d144c0ba9329cb335a5977
> Fix the UVC app on Windows

- depthai_demo.py
- depthai_helpers/config_manager.py
- depthai_sdk/src/depthai_sdk/managers/nnet_manager.py
> Fix streams to show resolve method

- README.md
- depthai_demo.py
- depthai_helpers/arg_manager.py
- depthai_sdk/src/depthai_sdk/utils.py
Added '--debug' option to connect to already booted devices and skips version check
CC: @szabi-luxonis @alex-luxonis as ping to use it if it comes handy
> Added 'debug' command line option

- depthai_demo.py
- requirements.txt
This PR adds a temperature shutdown mechanism that raises Overheat error if the device gets over 105* celsius
> Add temperature shutdown

- calibrate.py
Default timer after space is pressed is 5 seconds. Which can be changed using the argument `-cd <number of seconds>`
Ex: `python3 calibrate.py -s 3 -brd bw1098obc -db -cd 2`
> Added timer for capture. 

- apps/uvc/main.py
- callbacks.py
- depthai_demo.py
- depthai_helpers/config_manager.py
- depthai_helpers/metrics.py
- depthai_sdk/src/depthai_sdk/managers/nnet_manager.py
- tests/guided_manual_test.py
This reverts commit 8192b2566734233562c5472b8daa7e2c1d6a248b.
Keeps API stable.
Related: https://github.com/luxonis/depthai-experiments/issues/373
> Revert SDK NNetManager draw API

- apps/record/main.py
- apps/record/requirements.txt
- depthai_demo.py
- depthai_helpers/app_manager.py
- depthai_helpers/config_manager.py
- depthai_sdk/setup.py
- depthai_sdk/src/depthai_sdk/managers/arg_manager.py
- depthai_sdk/src/depthai_sdk/managers/encoding_manager.py
- depthai_sdk/src/depthai_sdk/managers/pipeline_manager.py
- depthai_sdk/src/depthai_sdk/record.py
- depthai_sdk/src/depthai_sdk/recorders/pyav_mp4_recorder.py
- tests/guided_manual_test.py
We should later also update SDK.
> Fixed args parser

- depthai_demo.py
> Include App in all cases

- batch/eeprom/NG9097_R4M2E3_BMI270_oak_d_pro_poe_af.json
- batch/eeprom/NG9097_R4M2E3_BMI270_oak_d_pro_poe_ff.json
- batch/eeprom/NG9097_R4M2E3_BMI270_oak_d_pro_w_poe.json
- batch/eeprom/NG9097_R4M2E3_BMI270_oak_d_s2_poe_af.json
- batch/eeprom/NG9097_R4M2E3_BMI270_oak_d_s2_poe_ff.json
- batch/eeprom/NG9097_R4M2E3_BMI270_oak_d_w_poe.json
> Fix EEPROM data for BMI270

- calibrate.py
Main change is:
```
if recent_left is None or recent_right is None or (recent_color is None and not self.args.disableRgb):
print("Continuing...")
```
```
if recent_left is None or recent_right is None or (recent_color is None and not self.args.disableRgb):
if time.time() - last_frame_time > 5:
if self.args.disableRgb:
print("Error: Couldn't retrieve left and right frames for more than 5 seconds. Exiting...")
else:
print("Error: Couldn't retrieve left, rigth and color frames for more than 5 seconds. Exiting...")
raise SystemExit(1)
cv2.waitKey(1)
continue
```
Otherwise the terminal just keeps spamming with `Continuing...`
> [Calibration] Graceful handling when frames cannot be retrieved

- .dockerignore
- .github/workflows/docker.workflow.yml
- Dockerfile
- README.md
- docker_dependencies.sh
Added CI for generating multiarch Docker images as well as created Dockerfile to facilitate creation of Docker Images that can run utilities in `depthai` repository
> Docker Image Support and CI

- depthai_sdk/src/depthai_sdk/classes/output_config.py
- depthai_sdk/src/depthai_sdk/oak_camera.py
- depthai_sdk/src/depthai_sdk/oak_outputs/xout.py
Added functionality to record visualized frames.
> Add record option.

- depthai_sdk/examples/age-gender.py
- depthai_sdk/src/depthai_sdk/oak_camera.py
- depthai_sdk/src/depthai_sdk/oak_outputs/xout.py
- depthai_sdk/src/depthai_sdk/utils.py
- depthai_sdk/src/depthai_sdk/visualize/configs.py
- depthai_sdk/src/depthai_sdk/visualize/objects.py
- depthai_sdk/src/depthai_sdk/visualize/visualizer.py
- Auto thickness adjustment
- Fix age-gender demo
- Replace kwargs with named arguments for visualizer's config methods
> Sdk complete refactor fixes

- .github/workflows/test_install_requirements.yml
Add a CI for testing if dependencies and requirements can be installed on the supported platforms.
> Test install requirements

- depthai_sdk/docs/source/components/imu_component.rst
- depthai_sdk/docs/source/components/nn_component.rst
- depthai_sdk/docs/source/features/packets.rst
- depthai_sdk/docs/source/features/replaying.rst
- depthai_sdk/docs/source/features/visualizer.rst
- depthai_sdk/docs/source/index.rst
- Minor changes in documentation
> Update docs for 1.9.1

- depthai_helpers/production_support_server_api.py
- install_requirements.py
> Revert "UI test tools production gen2 update boards"

- test_ui.py
I added a "Erase device" button in the startup dialog.
Clicking the button will open a new dialog with an option to erase a device. Any potential errors will be printed in the text box below.
> Erase device dialog

- depthai_sdk/docs/source/components/nn_component.rst
- depthai_sdk/docs/source/index.rst
- depthai_sdk/examples/NNComponent/age-gender.py
- depthai_sdk/examples/NNComponent/deeplabv3_person.py
- depthai_sdk/examples/NNComponent/emotion-recognition.py
- depthai_sdk/examples/mixed/car_tracking.py
- depthai_sdk/examples/replay/people-tracker.py
- depthai_sdk/setup.py
- depthai_sdk/src/depthai_sdk/__init__.py
- depthai_sdk/src/depthai_sdk/components/camera_component.py
- depthai_sdk/src/depthai_sdk/components/camera_helper.py
- depthai_sdk/src/depthai_sdk/components/nn_component.py
- depthai_sdk/src/depthai_sdk/components/nn_helper.py
- depthai_sdk/src/depthai_sdk/oak_outputs/normalize_bb.py
Fixed the 2-stage nn cropping issue - Remove the newH check in camera_helper.py when depthai core is fixed
Merge with PR: https://github.com/luxonis/depthai-experiments/pull/376
> Release 1.9.1.1

- depthai_sdk/docs/source/conf.py
- Update SDK version in docs config to 1.9.1.2
> Fix docs version

- .github/workflows/python-publish.yml
Workflow to publish depthai_sdk when release comes out
> Add publishing action

- depthai_sdk/src/depthai_sdk/components/nn_component.py
- Fix issue when config was not updated with Roboflow
> Fix runtime warnings with Roboflow

- depthai_sdk/examples/NNComponent/mobilenet_encoded.py
- depthai_sdk/examples/NNComponent/roboflow_integration.py
- depthai_sdk/examples/StereoComponent/stereo_encoded.py
- depthai_sdk/src/depthai_sdk/components/nn_component.py
- depthai_sdk/src/depthai_sdk/components/stereo_component.py
- depthai_sdk/src/depthai_sdk/oak_camera.py
- depthai_sdk/src/depthai_sdk/oak_outputs/xout.py
- depthai_sdk/src/depthai_sdk/recorders/video_writers/video_writer.py
- depthai_sdk/src/depthai_sdk/visualize/objects.py
Main changes:
- Added encoded disparity to `StereoComponent`
- Added encoded output to `NNComponent`
> Encoded disparity and NN outputs

- depthai_sdk/examples/StereoComponent/stereo.py
- depthai_sdk/examples/recording/stereo_record.py
- depthai_sdk/src/depthai_sdk/components/stereo_component.py
- depthai_sdk/src/depthai_sdk/oak_outputs/xout.py
- depthai_sdk/src/depthai_sdk/visualize/configs.py
- Add three levels for WLS filtering: low, medium, and high.
- Fix issues when parameters were handled incorrectly.
> Stereo WLS filtering levels

- depthai_sdk/setup.py
- depthai_sdk/src/depthai_sdk/oak_outputs/xout/xout_nn.py
- depthai_sdk/src/depthai_sdk/visualize/visualizer.py
- Fix issue when frame shape was incorrect
- Fix typo
> Hotfix (1.9.3.1)

- depthai_sdk/src/depthai_sdk/__init__.py
- Add utils and previews imports
> Fix imports for depthai_demo

- depthai_sdk/setup.py
- depthai_sdk/src/depthai_sdk/previews.py
- Make `import cv2` conditional (in case user doesn't have cv2 installed, app that doesn't use it shouldn't fail)
> Fix cv2 import

- depthai_sdk/src/depthai_sdk/args_parser.py
- depthai_sdk/src/depthai_sdk/components/stereo_component.py
- depthai_sdk/src/depthai_sdk/oak_camera.py
- depthai_sdk/src/depthai_sdk/readers/videocap_reader.py
> Updated Replay so it creates XLinkIn nodes at the start. 

- depthai_sdk/docs/source/features/ai_models.rst
- depthai_sdk/docs/source/quickstart.rst
> Started updated AI feature docs

- depthai_sdk/examples/recording/record_all.py
- depthai_sdk/src/depthai_sdk/args_parser.py
- depthai_sdk/src/depthai_sdk/components/camera_component.py
- depthai_sdk/src/depthai_sdk/components/camera_helper.py
- depthai_sdk/src/depthai_sdk/oak_camera.py
Some API additions so an example to record all streams at max resolution was easy to write.
> Improve the API for starting all cameras

- depthai_sdk/examples/recording/record_all.py
- depthai_sdk/src/depthai_sdk/record.py
- depthai_sdk/src/depthai_sdk/recorders/video_recorder.py
- depthai_sdk/src/depthai_sdk/recorders/video_writers/video_writer.py
Added an option to save videos w/o encoding when space is not an issue.
> Add an option for lossless saving of video streams

- depthai_helpers/app_manager.py
- depthai_helpers/cli_utils.py
- depthai_helpers/config_manager.py
- depthai_helpers/supervisor.py
- depthai_helpers/version_check.py
Reverted changes that removed depthai_helper scripts, required  by depthai_demo
PR that removed some scripts: https://github.com/luxonis/depthai/pull/1083
> Reverted changes that removed depthai_helper scripts

- calibrate.py
Fix fisheye model for really warped images. Temporary solution, but needs a long term solution.
> Fixing fisheye

- calibrate.py
Fixing the bug of changing the paths for dataset.  Tested by me and @CenekAlbl.
> Change path

- calibrate.py
- requirements.txt
Adding debug mode, where camera does not need to be connected, to be calibrated. Works only for process mode.
> Adding debug

- .github/workflows/test_install_requirements.yml
- removed already installed packages: (https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md)
> Fixing windows tests

- .github/workflows/test_install_requirements.yml
- depthai_demo.py
- depthai_sdk/requirements.txt
- requirements.txt
Also updated depthai-demo a bit so it doesn't throw warnings.
I don't know why windows (choco) tests fail, someone would need to look into that.
> Updated lib version

- launcher/choose_app_dialog.py
- launcher/launcher.py
removing the option to choose demo mode and running the viewer directly
> Launcher update

- depthai_sdk/src/depthai_sdk/components/nn_component.py
- depthai_sdk/src/depthai_sdk/components/nn_helper.py
Made it so SDK (=> viewer) doesn't crash if no internet access is available.
> SDK offline NN
