python-api/test_cnn.py

When an object is detected and then leaves the image, the Tensor label returned is typically far outside the list of label indexes (ex: 7552.0). This causes the `test_cnn.py` to crash.
This checks to ensure the index is within the available labels before applying the label text.
The exception:
```
File "test_cnn.py", line 85, in <module>
cv2.putText(frame, labels[int(e[0]['label'])], pt_t1, cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)
IndexError: list index out of range
```

Prevent test_cnn.py from crashing w/invalid Tensor label

---

python-api/calibrate.py
python-api/calibration_utils.py

This is a bit of an ugly "catchall": it allows you to overwrite the config `dict` passed to `depthai.create_pipeline()` in `calibrate.py` by passing thru a JSON-formatted string of config options. 
For example:
```
python calibrate.py -co '{"board_config": {"swap_left_and_right_cameras": true, "left_to_right_distance_cm": 9.0}}'
```
...will deep-merge those key/values on top of the default `config` dict.
This allows us to avoid defining a ton of arguments for potentially seldom-used options. 
/cc @Luxonis-Brian @Luxonis-Brandon

Pipeline Config options overwrite argument `-co` or `--config_overwrite``

---

consts/resource_paths.py

If an empty string (`''`) is passed as the `calibration_file` value, a default
calib setting will be used by DepthAI. Message from the console:
```
depthai: Calibration file is not specified, will use default setting;
```
So, I think we can collapse the file handling a bit.
/cc @Luxonis-Brian

Simplify default calib file handing

---

calibrate.py
depthai_helpers/calibration_utils.py
depthai_helpers/utils.py
test.py

This adds the ability to overwrite the default config via a script argument. It works the same as the calibrate.py.
Additionally:
* Puts utils in a dedicated `depthai_helpers` folder
* For utils shared by both calibrate and test, adds a depthai_helpers.utils module

Adds --config-overwrite to test.py

---

test.py

By default, the `COLORMAP_HOT` display is used.

Add support for colorized, grayscale, and raw depth map

---

test.py

Multiple DepthAI devices support, with device selection based on the host USB port.
Usage example:
```
python3 test.py -dev list
...
XLink initialized.
Detected 2 device(s):
2-ma2480     on USB port: 2
1.1-ma2480   on USB port: 1.1
```
`python3 test.py -dev 2`
`python3 test.py -dev 1.1`

Multiple DepthAI support

---

calibrate.py

This PR improves the overall performance of the calibration script and it's readability and adds some additional functionalities:
- Capture the frames only after spacebar is hit
- Stops the capture if it could not find the chessboard
- Marks the captured polygon green if the image was captured successfully (taken from #51, thanks @squeakus)
- Do not save the images if the chessboard was not found (also taken from #51, thanks again @squeakus)
- removed `--polygons` flag as it was not giving any relevant functionalities to the user.
This is a significant refactor, would love to hear your thoughts and if it works on your side @Luxonis-Brandon  and @Luxonis-Brian

Refactor the calibration script to make it faster and clearer

---

autostart/startupdemo

Simple change here, accompanied by a change in /home/pi/.config/autostart/runai.desktop in Raspbian, which will need to be updated manually for users who have an existing uSD with the old depthai-python-extras repo. All future images on uSDs that ship from Luxonis will have this change.

autostart fix for repo name change

---

depthai_helpers/calibration_utils.py

Change 'plane_depth' param to a large number (used 40000000.0 was 40.0), because this experimentally improves the "bad" calibration boards while not significantly affecting the "good" boards. TODO: understand *why* this is true...
Also, improvements to stereocalibrate flags to allow some additional parameter flexibility in the algo. These were also found experimentally to improve calibration outputs across "good" and "bad" PCBAs.

Fix address PCBA epipolar variation

---

calibrate.py

Resolves #63 
Adds `-iv` and `-ih` (with long-names `--invert-vertical` and `--invert-horizontal` respectively) that flips the displayed image - for calibration, still the "un-flipped" frame is passed

Add ability to invert the horizontal and vertical axis

---

calibrate.py

This PR resolves #64 
I assume that machine specs starting with `arm` and `aarch64` are embedded systems, as listed [here](https://stackoverflow.com/questions/45125516/possible-values-for-uname-m)

limit FPS on embedded platforms

---

calibrate.py
depthai.py
depthai_helpers/calibration_utils.py

1.
Data stored in EEPROM is printed when DepthAI starts, for example:
```
EEPROM data: valid (v3)
Board name     : BW1098OBC
Board rev      : R0M0E0
HFOV L/R       : 71.86 deg
HFOV RGB       : 68.7938 deg
L-R   distance : 7.5 cm
L-RGB distance : 3.75 cm
L/R swapped    : yes
L/R crop region: center
Calibration homography:
1.020374,   -0.009401,  -17.930922,
0.014302,    1.018133,  -26.645380,
0.000003,    0.000006,    1.000000,
```
or:
```
EEPROM data: invalid / unprogrammed
```
2.
The full resolution for Left/Right mono cameras is 1280x800, and cropping is applied to obtain 1280x720. Until now the cropping was done using the top region. This PR adds support for center cropping (better aligned with RGB). Note: to be enabled, this requires recalibration, as otherwise the depth quality is …

Display EEPROM data, center L/R cameras

---

depthai.py

Temperature metadata stream was always enabled, but on device side it was disabled.
This PR enables only when requested:
W/ option -s meta_d2h

add temperature metadata on-demand

---

calibrate.py
calibrate_and_test.py
depthai.py
depthai_supervisor.py

To avoid problems with wrong environment/python version this PR adds possibility to run scripts with any of the following commands:
python depthai.py
python3 depthai.py
./depthai.py
Tested on Linux.

Python3 shebang line; executable permission for python scripts

---

depthai.py

`from time import monotonic` got somehow deleted when PR https://github.com/luxonis/depthai/pull/106 was merged.
Adding it back, to fix the crash in the python script.

Add back time.monotonic import

---

depthai.py

In the code we parse tensors, which are stored in `TensorEntryContainer` and store them in a list `prev_entries`.
`TensorEntryContainer` (nnet_packet) went out of scope after parsing 
(after  `for _, nnet_packet in enumerate(nnet_packets): `), the reference was lost to it and it was deallocated, but the tensors parsed were pointing to the `TensorEntryContainer` object allocated on heap (dangling pointer). Any object allocated after TensorEntryContainer deallocation had a chance that it was allocated in the same memory space where `TensorEntryContainer` was before, thus corrupting tensors which were accessed through `prev_entries`.
This issue is clearly reproducible in `https://github.com/luxonis/depthai/tree/nn_left_right_BUGFIX` where the NN s for left camera are corrupted. They were …

Keep NN packet source alive while it's used to avoid dangling ptr/reference

---

README.md
depthai_helpers/cli_utils.py
requirements.txt

Add support for argument autocomplete on TAB pressing, like any other app.
`python3 -m pip install -r requirements.txt`
`echo 'eval "$(register-python-argcomplete depthai.py)"' >> ~/.bashrc`
Only bash is supported for now.
On macos run depthai from bash: from terminal: `bash` then follow instructions.
When pressing tab it will list all available arguments, and all available options for that argument, for example:
`./depthai.py -cnn` TAB will list all supported CNN models.
`./depthai.py -cnn mobi` TAB will autocomplete to mobilenet-ssd

Python command line autocomplete

---

requirements.txt

Currently, when trying to install requirements using `requirements.txt` file on Raspberry, it fails, since specified version is not available in Raspbian, example below:
```
pi@raspberrypi:~ $ pip3 install opencv-python==4.2.0.34
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting opencv-python==4.2.0.34
Could not find a version that satisfies the requirement opencv-python==4.2.0.34 (from versions: 3.4.2.16, 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.6.27, 3.4.7.28, 4.0.1.24, 4.1.0.25, 4.1.1.26)
No matching distribution found for opencv-python==4.2.0.34
```
We can fix this, by not specifying exact version of `opencv-python` but minimum required version - and in our case we rely on OpenCV version 4.
So simply changing `opencv-python==4.2.0.34` to …

Update requirements.txt for raspberry pi builds

---

requirements.txt

This PR resolves #168 
As specified [here](https://github.com/piwheels/packages/issues/59) the opencv-python version we're using requires a workaround due to an error
```
undefined symbol: __atomic_fetch_add_8
```
And the proposed workaround consists of adding an environment variable
```
LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1
```
However, if we downgrade the `opencv-python` version on RPi from `4.1.1.26` to `4.1.0.25`, the error does not occur and no workaround is needed

Fix requirements on RPi 

---

depthai_demo.py
requirements.txt

Since raspberry pi doesn't have a prebuilt open3d library. Conversion to point cloud and visualization is disabled for now.

open3d install and point cloud conversion for raspberry pi disabled.

---

depthai_helpers/config_manager.py
requirements.txt

Two stage NN was broken due to a small error in refactorization done for arg/config manager.
```
./depthai_demo.py -cnn face-detection-retail-0004 -cnn2 landmarks-regression-retail-0009 -cam left_right -sh 12 -cmx 12 -nce 2 
```
was broken.
The problem appeared only when the model was auto-compiled.
Calibration was also fixed when EEPROM was empty.

Two stage NN + calibration fix

---

depthai_demo.py

Users who use e.g. Ubuntu 16.04 can receive the following error when importing open3d
```
File "depthai_demo.py", line 28, in <module>
from depthai_helpers.projector_3d import PointCloudVisualizer
File "/home/lux/depthai/depthai_helpers/projector_3d.py", line 4, in <module>
import open3d as o3d
File "/home/lux/.local/lib/python3.5/site-packages/open3d/__init__.py", line 47, in <module>
from open3d.open3d_pybind import camera
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/lux/.local/lib/python3.5/site-packages/open3d/open3d_pybind.cpython-35m-x86_64-linux-gnu.so)
```
even if they didn't want to use PCL visualization, and simply ran `python3 depthai_demo.py`
This PR moves the import to the place where it's …

Change pcl import

---

depthai_helpers/arg_manager.py
depthai_helpers/config_manager.py
requirements.txt

Source code PR: https://github.com/luxonis/depthai-python/pull/53
New options for `-cam / --cnn_camera`: `rectified_left`, `rectified_right`, `rectified_left_right` (both L and R rectified).
Note: by default the rectified streams are mirrored, so depending on usecase this option may be needed: `-mirror_rectified false`

Option to run NN on stereo rectified streams

---

depthai_demo.py

Fix `-vv` / `--verbose` crash when `metaout` stream is enabled. Also display camera source for `disparity`/`depth`.
Should fix issue https://github.com/luxonis/depthai/issues/228
Example output for `./depthai_demo.py -vv -s previewout left right depth rectified_left metaout -sync -rgbf 20 -monof 20`:
```
[16.250735 NNet           ] 120.989991 314 rgb
[16.251078 previewout     ] 120.989991 314 rgb
[16.252138 left           ] 121.039615 274 left
[16.253608 right          ] 121.039640 274 right
[16.255058 depth          ] 121.039615 274 right (rectified)
[16.263112 rectified_left ] 121.039615 274 left
[16.299313 NNet           ] 121.039984 315 rgb
[16.299623 previewout     ] 121.039984 315 rgb
[16.300541 left           ] 121.089588 275 left
[16.301891 right          ] 121.089611 275 right …
```

Fix -vv / --verbose option for NN

---

depthai_demo.py
depthai_helpers/arg_manager.py
depthai_helpers/config_manager.py
depthai_helpers/version_check.py
requirements.txt

- Skip DepthAI library version check for local/development builds.
- Add an option:
```
-seq, --sync-sequence-numbers
Synchronize sequence numbers for all packets.
Experimental
```
- With `-vv`/`--verbose` print more metadata fields, and also print a header. Example for:
`./depthai_demo.py -s metaout previewout jpegout left right depth object_tracker rectified_left rectified_right color -vv -seq`
```
[hostTimestamp streamName] devTstamp seq camSrc width height Bpp
[0.736409 object_tracker ] 3.836959 1 rgb 648 1 1
[0.752393 previewout     ] 3.836959 1 rgb 300 300 3
[0.756711 color          ] 3.836959 1 rgb 1920 1080 1
[0.772088 NNet           ] 3.836959 1 rgb 3604 1 1
[0.772309 previewout     ] 3.870289 2 rgb 300 300 3
[0.772653 object_tracker ] 3.870289 2 rgb 648 1 1
[0.772730 color …
```

Gen1 updates

---

.gitignore
depthai_helpers/arg_manager.py
depthai_helpers/config_manager.py

This is mostly intended for quick experiments that modify only the device firmware, and it helps to skip the rebuild of the python wheel.
The `FIRMWARE` commit hash value will be provided by Luxonis (to ensure it is compatible with the host app), and can be hardcoded in https://github.com/luxonis/depthai/blob/85db9ff/depthai_helpers/config_manager.py#L17 (on a given branch)
or inputted by this command line option:
```
-fw FIRMWARE, --firmware FIRMWARE
Commit hash for custom FW, downloaded from Artifactory
```
The firmware specified is downloaded from [Luxonis Artifactory - device side](https://artifacts.luxonis.com/artifactory/luxonis-myriad-snapshot-local/depthai-device-side/) and cached locally inside the repo, in `.fw_cache` directory. Both normal (USB3-enabled) and USB2 variants of …

Custom firmware option

---

calibrate.py

With model zoo being fetched using downloader `calibrate.py` was not working since blob was not found. added a small fix to download `mobilenet-ssd` if not found during the calibration routine.

fixed missing blob error in calibrate.py

---

model_compiler/model_compiler.py

Should fix the issue #263  when the script is launched with other than `python3`, for example `python3.9`, where `python3` != `python3.9`

Use the same interpreter for child processes as for parent

---

requirements.txt

Source code PR: https://github.com/luxonis/depthai-python/pull/64
Should fix issue https://github.com/luxonis/depthai/issues/259
Tested by replacing this line: https://github.com/luxonis/depthai/blob/ddfe91b7/depthai_demo.py#L382
```diff
if __name__ == "__main__":
dai = DepthAI()
-    dai.startLoop()
+    while True: dai.startLoop()
```
and pressing `q` during streaming, to have the loop restart.
Also tested that the watchdog still works fine, by manually resetting the device while streaming.

Fix crash on 2nd device object delete

---

model_compiler/model_compiler.py

New blob converter is available here for now - http://69.164.214.171:8083/
It will be 8080 port when this PR is accepted and old blobconverter is removed

Add better error handling in model downloader & migrate to new BlobConverter

---

model_compiler/model_compiler.py

Hotfix for error introduced in #265 w/ python 3.6.
We don't need to capture the output from subprocess, it will be printed anyway.
https://github.com/luxonis/depthai/pull/265#discussion_r519072362

Hotfix for python3.6 failure w/ model downloader

---

depthai_helpers/calibration_utils.py

Suggestion on the image showing loop exiting behavior
The whole process is killed by ESC button, and there are no keys to exit the image showing loop in `show_rectified_images_two_calib`.
This is for making ESC only to exit the loop and the process will be kept on after exiting the loop.
Before
- [Space]: next image
- [ESC]: quit the process
- Other keys: no operation
Suggestion
- [ESC]: exit loop
- Other keys: next image

Change behavior of image showing loop

---

depthai_demo.py
requirements.txt

Source code PR: https://github.com/luxonis/depthai-python/pull/68
Device FW updates:
- fix potential crash with RGB 12MP (`-rgbr 3040`) + depth
- fix the cropping area for 4K (`-rgbr 2160`) - make it centered, it was top-left
Add some key controls for RGB manual exposure/focus:
```
Control:      key[dec/inc]  min..max
exposure time:     i   o    1..33333 [us]
sensitivity iso:   k   l    100..1600
focus:             ,   .    0..255 [far..near]
```

RGB camera fixes + key controls for manual focus/exposure

---

install_requirements.py

This PR adds the `--user` flag to install commands if the installation is system-wide (not from virtualenv)
Since the virtualenv itself does not allow the `--user` flag, failing with error
```
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```
an additional check is added to determine if the interpreter used by the user is from virtualenv or not
Tested on Linux (both system-wide and virtualenv) and Mac (both system-wide and virtualenv)

Use --user flag for system-wide installation

---

depthai_demo.py
requirements.txt

It was previously limited to about 33ms from device side.
To set larger exposures, the FPS need to be reduced accordingly (depthai_demo.py options `-rgbf` / `-monof`), for example 5 fps for max 200ms exposure.
Use `S` key to toggle between the cameras (`rgb` or `mono`) where the exposure control is applied. And change with:
```
```
For mono cameras, a flicker artifact could appear in the frame following a change in the exposure/iso value. This needs to be debugged.
For mono cameras, currently the max exposure that can be applied:
- 0.596s at  640x400
- 1.252s at 1280x720 or 1280x800 - however with the fps set below 1.0 there's a risk the watchdog could kick in and do a reset. Workaround: add `meta_d2h` to the list of streams, for example: `-s left right meta_d2h -monof 0.5`. Also if the …

Increase RGB/Mono manual exposure max limit

---

requirements.txt

Updated depthai lib/firmware to rotate the RGB camera view by 180° on OAK-1, and obtain a normal view with USB Type-C connector downwards.
Should fix issue https://github.com/luxonis/depthai/issues/200

Gen1: flip camera view on OAK-1

---

requirements.txt

Bump opencv version (and matching numpy version) to the latest.
When `4.4.0.46` was released Mac OS big sur was not out.
Tested on all platforms (RPI, Linux, Windows, MacOS)

Bump opencv version in requirements

---

README.md
depthai_helpers/projector_3d.py
install_requirements.py
requirements-optional.txt
requirements.txt

Currently, most of the cases when `install_requirements.py` fails are due to open3d library being not available.
This PR makes this dependency optional, as it's only needed with `-pcl` flag enabled (also added a prompt there if open3d is missing)

Make Open3D installation optional

---

calibrate.py
depthai_helpers/arg_manager.py
depthai_helpers/version_check.py

- Add `-fusb2` option to `calibrate.py` - enabling a workaround for issue https://github.com/luxonis/depthai/issues/305 (cherry-picked the commit mentioned there)
- Remove command-line options that can use `-brd / --board` as a simpler/safer replacement (making sure no option is missed):
- `-fv  / --field-of-view`
- `-rfv / --rgb-field-of-view`
- `-b   / --baseline`
- `-r   / --rgb-baseline`
- `-w   / --no-swap-lr`
- Set defaults to BW1098OBC / OAK-D if `-brd` is not specified
- Minor logging cleanup: don't print `Depthai required version` when it matches with `installed`, print just `installed`

Gen1 'depthai_demo' / 'calibrate' script updates

---

depthai_helpers/arg_manager.py

'landmarks-regression-retail-0009', 'facial-landmarks-35-adas-0002', 'emotions-recognition-retail-0003'
are not supposed to be run as first stage networks.
Note: age-gender-recognition can't be run as second stage network due to gen1 limitations. (it has 2 tensor outputs)

Set default mono resolution to 400p; Limit 1st stage cnn choices

---

requirements.txt

USB descriptor was improperly set up, causing enumeration failure with `-fusb2` / `--force_usb2` on Windows (more strict checks).
It shouldn't affect the behavior on macOS or Linux.
On Linux for example, `dmesg` was just reporting `unable to get BOS descriptor`, but the device worked fine.

Update Gen1 depthai: firmware fix for `-fusb2` on Windows

---

tests/tests_runner.py

Currently, also second stage NNs are being tested - this PR makes sure that only first stage NNs are checked

limit CNNs tested in run_tests.py

---

depthai_demo.py
depthai_helpers/arg_manager.py

This flag allows to get DepthAI usage info on the terminal during the runtime.
Example output logs
```
Drr used / total - 75.58 / 414.55 MiB
Cmx used / total - 2.37 / 2.50 MiB
LeonCss heap used / total - 33.33 / 46.35 MiB
LeonMss heap used / total - 5.07 / 27.40 MiB
Chip temperature - average: 35.35, css: 36.06, mss: 34.64, upa0: 35.11, upa1: 35.59
Cpu usage - Leon OS: 27.15%, Leon RT: 1.70 %
----------------------------------------
Drr used / total - 75.58 / 414.55 MiB
Cmx used / total - 2.37 / 2.50 MiB
LeonCss heap used / total - 33.33 / 46.35 MiB
LeonMss heap used / total - 5.37 / 27.40 MiB
Chip temperature - average: 37.77, css: 38.88, mss: 37.24, upa0: 37.94, upa1: 37.01
Cpu usage - Leon OS: 27.33%, Leon RT: 23.24 %
----------------------------------------
Drr used / total - 75.58 / …
```

add --report flag

---

depthai_helpers/config_manager.py
requirements.txt

This PR is testable with the changes from #377, but changes a different part of the script. 
During tests of the mentioned PR, in one of the runs we misstyped `deeplabv3_person` (whereas the correct name should be deeplabv3**p**_person) in the cnn param, and it resulted with the following error
```
File "depthai_demo.py", line 569, in <module>
nn_manager = NNetManager(
File "depthai_demo.py", line 195, in __init__
self.blob_path = BlobManager(model_dir=self.model_dir, model_name=self.model_name).compile(conf.args.shaves)
File "/home/erik/Luxonis/depthai/depthai_helpers/config_manager.py", line 287, in compile
return blobconverter.from_zoo(name=self.model_name, shaves=shaves)
File "/home/erik/.local/lib/python3.8/site-packages/blobconverter/__init__.py", …
```

Add a better handling of misspelled model names when using model zoo

---

callbacks.py
depthai_demo.py
depthai_helpers/arg_manager.py
depthai_helpers/utils.py

This PR implements support for custom callbacks that users can add in order to customize the behavior of the demo script.
For example, if a user would like to add a label to each frame, that would indicate its origin, he can do it now without digging into a code, but modifying the `on_show_frame` method inside `callbacks.py` into the following
```python
from cv2 import cv2
def on_show_frame(frame, source):
cv2.rectangle(frame, (frame.shape[1] - 100, frame.shape[0] - 30), (frame.shape[1], frame.shape[0]), (255, 255, 255), cv2.FILLED)
cv2.putText(frame, source, (frame.shape[1] - 80, frame.shape[0] - 10), cv2.FONT_HERSHEY_TRIPLEX, 0.5, (0, 0, 0))
```
Which will result in the following output
Supported callbacks:
- `on_new_frame(frame, source)` - called when a new frame arrives from the …

Add custom callbacks support, allowing to customize demo script behaviour

---

requirements-optional.txt
requirements.txt

Fixes [broken requirements](https://github.com/luxonis/depthai/pull/388/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R2) for ARM devices (rpi2/3/zero)

Install different opencv version for arm devices

---

depthai_demo.py
depthai_helpers/managers.py

This PR splits the managers from the demo code itself. Some minor fixes included, like constant detection flip when using `rectified_left` or `rectified_right` streams

Refactor demo code to extract managers to a separate file

---

depthai_demo.py
depthai_helpers/arg_manager.py
depthai_helpers/managers.py
requirements-optional.txt
requirements.txt

This PR adds two new flags:
- `-enc / --encode` flag that accepts the camera names to be recorded and also can contain their FPS (defaults to 30). You can pass either just `-enc left` (encode left camera with 30 FPS) or `-enc left right` (encode left and right camera with 30 FPS) or `-enc color left,10 right,10` (encode color camera with 30 FPS and left / right cameras with 10 FPS)
- `-encout / --encode_output` specifies path to the output directory where the encoded files will be stored (in a form of `<camera_name>.h264` )
```
$ ./depthai_demo.py --help
[...]
-enc ENCODE [ENCODE ...], --encode ENCODE [ENCODE ...]
Define which cameras to encode (record) 
Format: camera_name or camera_name,enc_fps 
Example: -enc left color 
Example: -enc color right,10 left,10
-encout ENCODE_OUTPUT, …
```

Add the ability to encode (record) camera output

---

depthai_demo.py
depthai_helpers/arg_manager.py
depthai_helpers/config_manager.py
depthai_helpers/managers.py
requirements-optional.txt
requirements.txt

With this PR:
- new sliders were added below depth, disparity and disparity_color previews. They can adjust disparity confidence threshold, bilateral sigma and left right check threshold. Trackbars are in sync, so if we update e.g. the confidence on one slider, other will get updated too
- on the same previews, a new box was added specifying the current median filter used. Users can use a different filter with`m` key. Future dynamic configuration options (like enabling L/R check or subpixel) can be added in this box too
- Improved handling of depth frames (to be the same as is [here](https://gist.github.com/alex-luxonis/b8b3f900ea27e42ded37c70eeb814bb7#file-sub_pixel-py-L98))
- Fixed bug with incorrect handling of `-s / --show` parameter that displayed more frames than was requested by …

Improve depth quality and allow real-time configuration

---

depthai_helpers/managers.py

Use defaults for baseline, mono FOV, focal distance

Fix a crash with calibration missing on OAK-D boards

---

depthai_helpers/managers.py

1. Fix a typo preventing `-enc color` to work:
`"AttributeError: 'types.SimpleNamespace' object has no attribute 'pm'"`
2. Fix `-enc color -rgbr 3040`, use video output resolution, not camera's, was crashing with:
`RuntimeError: , LRT: 'VideoEncoder(9) - VideoEncoder out of resources.'`
(as `video` is cropped from 4056x3040 to 3840x2160 by default)
Still, `python3 depthai_demo.py -enc color -rgbr 3040` crashes now with:
`RuntimeError: , LRT: 'ColorCamera(4) - Out of memory while creating pool for 'still' frames. Number of frames: 4 each with size: 18385920B'`
But works disabling some other resources, like: `python3 depthai_demo.py -enc color -rgbr 3040 -dd`
We'll need to reduce the pool size for `still`/other outputs in FW, and/or make it configurable.

Fix `-enc color`

---

depthai_demo.py
depthai_helpers/arg_manager.py
depthai_helpers/config_manager.py
depthai_helpers/managers.py

This PR introduces performance improvements by using MJPEG encoding before sending the frames over XLink and then decoding them on the host using OpenCV `imdecode` method.
Due to the current encoder limitations, not all of the preview streams have the encoding enabled:
- :x: `nn_input` (the `passthrough` output from the nn)
- :heavy_check_mark: `color`
- :heavy_check_mark: `left`
- :heavy_check_mark: `right`
- :heavy_check_mark: `rectified_left`
- :heavy_check_mark: `rectified_right`
- :x: `depth_raw`
- :x: `depth`
- :heavy_check_mark: `disparity`
- :heavy_check_mark: `disparity_color`
One important change that had to be introduced is that now the `color` stream is taken from ColorCamera `video` output instead of `preview` (since only `video` output can be MJPEG encoded at the moment). …

Improve PoE performance by introducing MJPEG encoding for streams

---

depthai_demo.py
depthai_helpers/config_manager.py
depthai_helpers/managers.py

This PR addresses improvements ideas from #433.
With this PR:
- RGB preview image is now scaled before any overlay is applied (reported [here](https://github.com/luxonis/depthai/pull/433#issuecomment-890573026))
- Applied text printing improvements (reported [here](https://github.com/luxonis/depthai/pull/433#issuecomment-890580600))
- If low bandwidth mode is detected (PoE usecase), it will use `disparity_color` stream by default instead of `depth`, because the latter one is not yet encodable with MJPEG

Add demo tweaks

---

depthai_helpers/utils.py
resources/nn/deeplabv3p_person/handler.py
resources/nn/openpose2/handler.py

This PR fixes the` openpose2` neural network, it crashed on main with
```
File "./depthai_demo.py", line 264, in <module>
nn_data = nn_manager.decode(in_nn)
File "/Users/leeroy/depthai/depthai_helpers/managers.py", line 469, in decode
return self.handler.decode(self, in_nn)
File "/Users/leeroy/depthai/resources/nn/openpose2/handler.py", line 152, in decode
valid_pairs, invalid_pairs = getValidPairs(outputs, w, h, detected_keypoints)
File "/Users/leeroy/depthai/resources/nn/openpose2/handler.py", line 46, in getValidPairs
pafA = outputs[0, mapIdx[k][0], :, :]
IndexError: index 47 is out of bounds for axis 1 with size 46
```
The source of this issue was the `[::-1]` transformation of tensor dimensions. The bug that it resolved was fixed in the latest API …

Fix OpenPose nn

---

resources/nn/deeplabv3p_person/handler.py
resources/nn/openpose2/handler.py

This PR fixes the nn overlay issue reported in #435 .
Due to this, both deeplabv3p_person and openpose2 were displaying it's results on larger frames with scaling issue (they were not showing the results correctly)
Now, the openpose2 shows correct output on the color preview (the results are off on the depth preview due to no rgb-depth alignment)
Also, the deeplab network is now correctly presenting it's results too

Fix OpenPose & Deeplab nn mapping

---

requirements.txt

With the `1.0.0` version of the blobconverter, we're using updated API url - blobconverter.luxonis.com.
Versions prior to `1.0.0` stopped working after the website transition, but FWIW they can still be used if we set the URL manually (although I'd recommend to update to latest version)
```diff
import blobconverter
+ blobconverter.set_defaults(url="http://blobconverter.luxonis.com")
```

Update blobconverter to 1.0.0

---

install_requirements.py

This PR introduces 2 improvements to `install_requirements.py` file:
- Throws a warning if user is using RPi and Python 3.7 or 3.9 is detected - there are no prebuilt wheels for OpenCV and installation process can take some time
- Throws an error if `pip` package is not installed with a link to install instructions
- Throws an error if script is invoked with Python 2 (sometimes it's the default `python` on old Ubuntu / RPi)

Improve install_requirements.py

---

install_requirements.py

This PR introduces a better handling for M1 chips in `install_requirements.py` file. Will throw an error, as we don't have prebuilt binaries anyways, but will also provide a link to discuss thread with a solution
I'll move this check together with #448 into depthai-python installer later

Add an error and solution link when detected M1 chip

---

requirements.txt

In previous version of `pytube` we recieved this error:
```Traceback (most recent call last):
File "depthai_demo.py", line 31, in <module>
conf.downloadYTVideo()
File "/home/erik/Luxonis/depthai/depthai_helpers/config_manager.py", line 194, in downloadYTVideo
raise RuntimeError("Unable to download YouTube video. Please try again")
RuntimeError: Unable to download YouTube video. Please try again
```
Updating `pytube` version to latest fixed this issue.

Updated version of pytube - so downloading of yt videos works again

---

depthai_helpers/managers.py
resources/nn/deeplabv3p_person/handler.py

This PR resolves #456 and adds a proper handling both for video and full-fov input.
Can be tested using:
- (without full FOV): `python3 depthai_demo.py -s color nn_input -cnn deeplabv3p_person -dff`
- (with full FOV): `python3 depthai_demo.py -s color nn_input -cnn deeplabv3p_person`
- (on YT video): `python3 depthai_demo.py -vid https://www.youtube.com/watch?v=lFlSUUnzLv0 -cnn deeplabv3p_person --sync`

Fix deeplabv3p_person preview on video

---

tests/guided_manual_test.py

This PR introduces a new script for testing - `tests/guided_manual_test.py`. This is a simple OpenCV script that serves as a helper tool when testing the DepthAI device and/or demo script.
The first screen allows selecting desired test areas
Then, one by one, the demo script is being run and one has to mark whether the test succeeded or not.
After all of the tests from the selected category are run successfully, a success message appears and the user is being redirected back to the menu

Add manual testing script

---

depthai_demo.py
resources/nn/road-segmentation-adas-0001/handler.py
resources/nn/road-segmentation-adas-0001/road-segmentation-adas-0001.json

This PR adds a `road-segmentation-adas-0001` handler to depthai-demo. Thanks to @franva for his pointers in #455 that made this PR easier to implement.
```
depthai_demo.py -cnn road-segmentation-adas-0001 -vid https://www.youtube.com/watch?v=lCmuKhHVAIg --sync
```

Add road-segmentation-adas-0001 handler

---

depthai_helpers/managers.py

This PR improves FPS calculations - as suggested by @alex-luxonis, `deque` was used and the average FPS is now more reliable.
Running the same command (`python3 depthai_demo.py`) in this PR printed
```
=== TOTAL FPS ===
[color]: 35.3
[depth_raw]: 33.1
[depth]: 33.1
[nn]: 32.3
```
Whereas on `main`
```
=== TOTAL FPS ===
[color]: 27.9
[depth_raw]: 27.6
[depth]: 27.6
[nn]: 27.9
```

Fix FPS calculation on host

---

calibrate.py

On RPi3 / CM3, by running calibration on all cameras it was observed that image capture (by pressing Space) was unresponsive. Reducing the FPS seems to resolve the issue.

Add `-fps` option to `calibrate.py`

---

depthai_demo.py
depthai_helpers/arg_manager.py
depthai_helpers/managers.py
requirements.txt

Use case:
Running as :
```
python3 depthai_demo.py -s left right -monor 400 -monof 118 -dnn -dd --xlink_chunk_size 0
```
instead default chunk size (FW specific, currently 64KB) increases FPS from 100 to 118 for both cameras.

Bump depthai version to 2.10.0.0; add xlink chunk size config

---

depthai_helpers/config_manager.py
depthai_helpers/managers.py

Also in `config_manager.py` we should remove the helper function `def maxDisparity(self):` and instead use `stereo.getMaxDisparity()`

Fixed max (normal) disparity to 95 (0..95)

---

requirements.txt

The default setting ( `cam_rgb.setImageOrientation(dai.CameraImageOrientation.AUTO)` ) will default now to `ROTATE_180_DEG` (in order to match how the camera module is mounted inside the device).

Fix default camera orientation for OAK-1-PoE, was rotated

---

README.md
depthai_demo.py
depthai_helpers/arg_manager.py
depthai_helpers/config_manager.py
depthai_helpers/managers.py
tests/guided_manual_test.py

This PR adds the `-camo / --camera_orientation` flag that allows setting camera orientation property on mono and color cameras.
Usage:
```
-camo CAMERA_ORIENTATION [CAMERA_ORIENTATION ...], --camera_orientation CAMERA_ORIENTATION [CAMERA_ORIENTATION ...]
Define cameras orientation (available: AUTO, NORMAL, HORIZONTAL_MIRROR, VERTICAL_FLIP, ROTATE_180_DEG) 
Format: camera_name,camera_orientation 
Example: -camo color,ROTATE_180_DEG right,ROTATE_180_DEG left,ROTATE_180_DEG
```

Add -camo / --camera_orientation flag

---

README.md
depthai_helpers/arg_manager.py
depthai_helpers/config_manager.py
tests/guided_manual_test.py

This PR adds the option to set manually the bandwidth.
By default, it's set to `auto` that will resolve the optimal bandwidth automatically but can be also used with `high` or `low` values to force either high or low bandwidth mode respectively

Add -bandw / --bandwidth argument

---

depthai_helpers/managers.py
tests/guided_manual_test.py

This PR fixes `-rgbr 3040 -bandw low` use case, where RGB camera is ran at 12 MP mode but the output stream gets encoded.
TODO - we currently use only video output stream, where we could use isp or raw outputs too for different preview options

Fix encoding at 3040 resolution mode

---

depthai_sdk/docs/source/api.rst
depthai_sdk/docs/source/getting-started.rst
depthai_sdk/docs/source/index.rst
depthai_sdk/docs/source/modules-list.rst

This PR adds the overview on top of the API page

 Update API docs to include classes listing on the top

---

resources/nn/openpose

Symlink `resources/nn/openpose` is pointing to a previously removed location `resources/nn/human-pose-estimation-0001/`

Removed an invalid symlink

---

depthai_sdk/requirements.txt
install_requirements.py
requirements.txt

Adds `--prefer-binary` to packages, to prefer precompiled wheels over latest source.
Brings improvements from: https://github.com/luxonis/depthai-python/pull/401
Removed dependencies for opencv-python/contrib specific versions, since SDK already contains them, and we don't hard define opencv version in `depthai-python` neither.
Please test on various platforms.
Why blobconverter version is not set to the latest ? Mainly changes from here: https://github.com/luxonis/depthai/pull/510/files
Pushed hotfix here: https://github.com/luxonis/depthai/commit/a46ad95744d8175f1c87bf8cd92c7423a84b8607
Note, there is an issue between opencv-python and opencv-contrib-python using latest wheels, QT5 related, need to look into it.

Update requirements installer

---

README.md

This PR adds a demo GIF with a link to YouTune showing an example demo run
[![depthai demo](https://user-images.githubusercontent.com/5244214/142426845-82f5f8fd-ad1a-4873-97a5-2b3fcdb0ca2e.gif)](https://www.youtube.com/watch?v=sCZpsFQBffk) 
Tried to add a higher-resolution GIF, but GitHub routes all images via https://camo.githubusercontent.com/ (even for external sourced), and if a file exceeds the size limit (10MB) it will raise "Content length exceeded" error and not return an image (404)

Add demo GIF showing GUI usage

---

depthai_demo.py

@alex-luxonis , do we intend to merge this?
```
Failed to create vertex shader: Error 0x80070057: The parameter is incorrect.
Failed to build graphics pipeline state
```
(certain systems only?)

Add a workaround for GUI blank window on Windows:

---

README.md
depthai_demo.py
depthai_helpers/metrics.py
gui/main.py
gui/views/MiscProperties.qml
gui/views/root.qml
log_system_information.py
requirements-optional.txt
requirements.txt

This PR adds the anonymous usage statistics aggregation to our demo.
Before first run, it asks for user permission to collect the data as below

Add statistics aggregation

---

depthai_helpers/metrics.py

If a call to gather statistics fails, it shouldn't affect the demo runtime. This PR fixes this case

Fail silently if metrics aggregation fails

---

depthai_helpers/metrics.py

With this PR, the MXID of PoE devices is resolved correctly in metrics aggregation

fix reporting for PoE devices

---

requirements.txt

Also upgrades `requests` to latest - fixing vulnerabilities: https://github.com/luxonis/depthai/pull/545
Note: after installing `pyrebase4`, if the package `pyrebase` is somehow uninstalled, `pyrebase4` would stop working, needing to be reinstalled with `--force-reinstall`, or removed first - similar issue as with `opencv-python` and `opencv-contrib-python`. This isn't separately handled yet.

Fix installing requirements on Windows: `pyrebase` -> `pyrebase4`

---

depthai_sdk/docs/source/getting-started.rst

This PR fixes links visible below

fix broken example usages links in SDK docs

---

depthai_demo.py
depthai_helpers/arg_manager.py

To enable RPi to work with latest demo, until we migrate to Qt5 we will still use the OpenCV render methods to display camera previews.
It will switch to this mode by default on RPi, and can be enforced with `-gt / --guiType` parameter accepting either `qt`, `cv` or `auto`.

Allow to specify which render backend to use (-gt / --guiType)

---

depthai_sdk/requirements.txt

Numpy `1.19.5` is the latest wheel that supports `python3.6`.

Install numpy version based on python version

---

requirements.txt

This PR introduces less strict version specification for PyQt5, requiring just PyQt5 5.x. Resolves #562

use better requirements specification for PyQt5

---

resources/nn/human-pose-estimation-0001/handler.py
resources/nn/human-pose-estimation-0001/human-pose-estimation-0001.json

This PR introduces `human-pose-estimation-0001`, providing similar output as `openpose2` network. Resolves #557

Add human-pose-estimation-0001 support

---

gui/views/AIProperties.qml
gui/views/CameraProperties.qml
gui/views/DepthProperties.qml
gui/views/MiscProperties.qml

In this PR, using a little hack, I was able to make all labels clearly visible in Qt UI.

Tweak QT UI colors

---

depthai_sdk/src/depthai_sdk/managers/pipeline_manager.py
depthai_sdk/src/depthai_sdk/managers/preview_manager.py
depthai_sdk/src/depthai_sdk/previews.py

When `disparity` was requested with low-bandwidth mode, it caused Out Of Memory error due to too many encoders being created. This PR disables `disparity` stream encoding when in low-bandwidth mode, so that 3 video encoders are created at once
Also, fixes default colormap used in preview manager to use an improved one

disable disparity encoding to prevent OOM issue

---

depthai_demo.py
requirements.txt

Currently, on Ubuntu 18.04, users running our demo will experience the following error (reported here - https://github.com/luxonis/depthai/issues/568)
```
QObject::moveToThread: Current thread (0x20b69f0) is not the object's thread (0x20e92f0).
Cannot move to target thread (0x20b69f0)
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/burner1/.local/lib/python3.6/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
This PR enables Qt GUI to work on this OS but requires setting an env flag prior.
The root cause of this issue is the conflict between the installed Qt version and the Qt version installed by OpenCV. To solve this, I …

Ubuntu 18.04 fix

---

depthai_sdk/src/depthai_sdk/managers/pipeline_manager.py

Some NNs require BGR inputs. Add setColorOrder to createColorCam in pipeline manager so this is easily configurable in the DepthAI SDK.

Add ColorOrder property to createColorCam in pipeline manager

---

depthai_helpers/supervisor.py

This PR fixes the WIndows issue when the path to the interpreter was containing spaces - e.g. `C:\Program Files`. Now, the path is quoted to prevent it

add fix for Windows paths

---

requirements.txt

This PR solves the reported issue on Windows, by preventing 5.15.6 from being installed and thus mitigated the issue below
```
File "D:\depthai\depthai_demo.py", line 893, in <module>
runQt()
File "D:\depthai\depthai_demo.py", line 493, in runQt
from gui.main import DemoQtGui, ImageWriter
File "D:\depthai\gui\main.py", line 5, in <module>
from PyQt5.QtQml import QQmlApplicationEngine, qmlRegisterType, qmlRegisterSingletonType, QQmlEngine
ImportError: DLL load failed while importing QtQml: The specified module could not be found.
```

exclude latest version of Qt due to Windows issue

---

depthai_demo.py
depthai_helpers/supervisor.py
gui/views/AIProperties.qml
gui/views/CameraPreview.qml
gui/views/CameraProperties.qml
gui/views/DepthProperties.qml
gui/views/MiscProperties.qml
gui/views/root.qml
install_requirements.py
requirements-optional.txt

This PR adds:
- Adds automatic handle for OPENBLAS_CORETYPE env variable setting for Jetson
- Downgrades QtQuick.Layouts to `1.3` to be available on Ubuntu 18.04
- Adds a correct exception if Python 2 is used
- Disables Qt backend by default on Jetson platforms due to Qt issue (ImageWriter is not painting the frames and it's width accessed from Python is negative)

Release tweaks

---

launcher/windows/installer_win64.iss
launcher/windows/src/create_shortcut.ps1

Single arguments don't need to be escaped otherwise the path contains the actual `"` quotes, which makes it invalid.

Fixes for Start Menu entry and shortcut icon

---

depthai_sdk/src/depthai_sdk/managers/pipeline_manager.py

Internal discussion about this subject:
https://luxonis.slack.com/archives/C012N7HNN4W/p1637887232073700
Demo is running at 30 fps again.

Disable stereo runtime mode switch since it allocates resources for worst case

---

apps/uvc/main.py
depthai_helpers/app_manager.py
depthai_helpers/arg_manager.py
requirements.txt

in this PR:
- Setup and terminate process is modified to correctly handle different OSes (tested on Windows and Mac)
- Removed argcomplete dependency (as we're moving more into GUI and having it listed would require demo apps to have it as well)
- Enabled same CLI arguments parsing for the apps as it is now for the demo
- Disabled UVC app is connection speed is USB2 due to #616

Enable CLI params in apps, tweak app setup and termination and disable UVC app with USB2 connections

---

depthai_demo.py

This issue resolves a case when `depthai_sdk` package could not be found - either due to not installing requirements or `depthai_sdk` package installation fails

Append both demo directory and sdk into path before imports

---

.github/workflows/demo.workflow.yml
launcher/README.md
launcher/windows/installer_win64.iss
launcher/windows/version.txt

- Added versioning to installer that matches depthai demo
- Added logging of powershell scripts that install some requirements during installation process 
- Enabled logging by default and added a troubleshooting section to describe where to find the logs
Note: By default, the version is set to `1.0-dev`. For non-release action builds it gets set to `1.0-[commit hash]` and `[version]` for releases

Installer improvements

---

depthai_helpers/config_manager.py

This PR changes the warning message about missing udev rules to more user-friendly one

update missing udev rules warning

---

install_requirements.py

This PR should resolve PyQT5 installation issue reported in https://github.com/luxonis/depthai/issues/627

Add html5lib support for pip install to avoid PyQt5 installation issue

---

depthai_sdk/setup.py

The url for the depthai-sdk is broken (because it has been modified), as a result the homepage link in pypi (https://pypi.org/project/depthai-sdk/) is also broken. 
This pull just updates the link in the setup.py for the depthai_sdk.

Fix depthai-sdk broken url link

---

requirements.txt

Release notes: https://github.com/luxonis/depthai-python/releases/tag/v2.15.1.0
https://github.com/luxonis/depthai/pull/665 will add more features about overheat reporting.

Update `depthai` to latest release 2.15.1.0

---

depthai_sdk/src/depthai_sdk/managers/nnet_manager.py

This PR adds the `useImageManip` flag to `createNN` function, which allows to disable creating the ImageManip before the neural network (requires the user to make sure the frames are in a correct resolution for NN)

Add useImageManip flag to NNetManager

---

depthai_demo.py
depthai_helpers/config_manager.py
depthai_sdk/src/depthai_sdk/managers/arg_manager.py
requirements.txt

Also adding the options `720` and `800` to `-rgbr`/`--rgbResolution`, and defaulting to `800` (instead of `1080`) for OV9782.

depthai 2.17.0.0 - supports new S2/Pro devices, OV9782 as RGB/center camera

---

depthai_demo.py
depthai_sdk/src/depthai_sdk/managers/arg_manager.py
depthai_sdk/src/depthai_sdk/managers/pipeline_manager.py

Add a command line option to override the camera tuning blob to use, for example as:
`-tun path/to...../tuning_color_ov9782_wide_fov.bin`
More details about the camera tuning: https://docs.luxonis.com/projects/api/en/latest/tutorials/camera_tuning/
___
Use case: new tuning blob added at the link below, that fixes OV9782 (color global shutter) color cast issues at very low exposure times (example: bright daylight).
https://artifacts.luxonis.com/artifactory/luxonis-depthai-data-local/misc/tuning_color_ov9782_wide_fov.bin
(note: this tuning currently doesn't support mono cameras, so they have to be disabled, and only the color camera enabled)
Can be tested as (extra options mainly for disabling mono cameras):
- initial:
```
python3 depthai_demo.py -s color -gt cv -dd -dnn
```
- with the new …

depthai_demo: add `-tun`/`--cameraTuning` option

---

dynamic_recalibration.py

Intrinsic parameters of the camera are unlikely to change after factory calibration, however extrinsic calibration can change, if the casing was removed, PCB bent etc.
Dynamic recalibration can correct camera rotation without having to perform a full calibration.
TODO:
-Handle different stereo max resolutions (e.g. OAK-D-Lite 480p max).
-Cleanup code
-Experiment with extra filtering to reduce epipolar error

Add initial dynamic recalibration

---

requirements.txt

To support latest boards.
Users were reporting that the board received doesn't work, because demo is still at 2.17.1.0.
Will make a release too.

Update depthai version to 2.17.3.0

---

depthai_helpers/config_manager.py

PR related to: https://luxonis.youtrack.cloud/issue/C-383
Issue was not with usb used, but rather the bandwidth. Fixed so now desparity is always used (and not depth) regardless of bandwidth.

Always show disparity

---

depthai_sdk/docs/source/features/ai_models.rst
depthai_sdk/docs/source/features/components.rst
depthai_sdk/examples/StereoComponent/stereo_record.py
depthai_sdk/examples/recording/encoder_preview.py
depthai_sdk/examples/replay/youtube-download.py
depthai_sdk/src/depthai_sdk/classes/output_config.py
depthai_sdk/src/depthai_sdk/components/nn_component.py
depthai_sdk/src/depthai_sdk/oak_outputs/syncing.py
depthai_sdk/src/depthai_sdk/oak_outputs/xout.py
depthai_sdk/src/depthai_sdk/recorders/abstract_recorder.py
depthai_sdk/src/depthai_sdk/recorders/video_recorder.py
depthai_sdk/src/depthai_sdk/recorders/video_writers/av_writer.py
depthai_sdk/src/depthai_sdk/recorders/video_writers/file_writer.py
depthai_sdk/src/depthai_sdk/recorders/video_writers/video_writer.py

- Fixed the errors that didn't allow user to record depth/disparity using `oak.visualize(..., record='...'))`
- Also fixed the problem with recording disparity data, and saving depth data (they were saved as `file_name.None`, now it's `file_name.dat`

Fix stereo recording

---

apps/uvc/requirements.txt

The 2.13.3.0 prebuilt library wasn't found on windows 11 python 3.8.

Update UVC app to latest gen2_uvc branch

---

.github/workflows/test_install_requirements.yml

Test different python versions as well. 
I didn't include versions for fedora, since `setup-python` action doesn't work out of the box
in containers in some cases, but we have the Fedora listed as supported by the community only officially,
so testing only "stock" pythons for Fedora should be fine.

Add python versions workflows

---

test_ui.py

The error showd when running the program with unflashed OAK-D-LITE because I was trying to read the EEPROM when none were flashed yet.
To fix the issue I added `orDefault` to `readCalibration` and `readFactoryCalibration` calls. This made the error disapear but logged an empty EEPROM. So I moved the EEPROM reading code further down the code path where in all cases the device is flashed.
Also I removed the duplicated function `flash_eeprom` with prior discussion with @alex-luxonis (see 11acce4d30ecad83958cc8d899c50a2f7b5e34fc), because at first I thought it could be a good place to store the EEPROM data for logging. But later I decided to move the logging even further down the code path. If the removal poses to much risk, we can revet the commit.

Fix exceptions that occured because of reading the EEPROM data at inappropriate time

---

test_ui.py

If the `DEPTHAI_BOARDS_PRIVATE_PATH` env var is set the private boards will appear along with the public boards instead of replacing them.
While implementing the feature I noticed some dead code and removed it here 4aef6e2b8a98c73e8a67012cd2f8ae0494e806cc.

Add support for private boards

---

entrypoint/depthai_launcher

- if venv not found in default directory, ask user to input depthai venv path
- entrypoint folder added to depthai
- depthai_launcher.sh added to entrypoint
- launcher script inferes the WORKING_DIR and depthai dir from the fact that entrypoint is in env and structure is:
working dir/depthai/entrypoint

entrypoint folder added to depthai

---

.gitignore
depthai_sdk/examples/mixed/sync_multiple_outputs.py
depthai_sdk/setup.py
depthai_sdk/src/depthai_sdk/classes/output_config.py
depthai_sdk/src/depthai_sdk/components/camera_component.py
depthai_sdk/src/depthai_sdk/components/nn_component.py
depthai_sdk/src/depthai_sdk/components/stereo_component.py
depthai_sdk/src/depthai_sdk/oak_camera.py
depthai_sdk/src/depthai_sdk/oak_outputs/xout_base.py

> Please note that I am not very familiar with the codebase so if there is something I have missed I am open to changing the implementation or even closing the request.
Right now it seems to be very hard to know from which camera (left, right, rgb, ...) a packet came from.
Take a look at this example:
```python
color = oak.create_camera('color')
left = oak.create_camera('left')
right = oak.create_camera('right')
oak.sync([color.out.main, left.out.main, right.out.main], callback=lambda p: print(p))
```
As you can see the frames are labeled with "0_preview", "1_out", "2_out" which is not very developer friendly. Ideally, I would like to have the streams named the same as the camera source ("color", "left", …

Added an option to name the streams

---

depthai_sdk/src/depthai_sdk/oak_device.py

Static variables cause unwanted behavior
shared streams across multiple OakCamera instances

OakDevice bug fix

---

apps/uvc/main.py
apps/uvc/requirements.txt

Now it works for macOS as well (prebuilt depthai wheels). Note that now the uvc app throws errors every so often, even though still capture is never triggered, but this can be ignored:
```[18443010D116631200] [1.3] [47.464] [ColorCamera(0)] [error] Still capture ignored, as the output is not connected
[18443010D116631200] [1.3] [47.497] [ColorCamera(0)] [error] Still capture ignored, as the output is not connected
[18443010D116631200] [1.3] [47.531] [ColorCamera(0)] [error] Still capture ignored, as the output is not connected```

Updated depthai for UVC app

---

.github/workflows/test_install_requirements.yml
depthai_sdk/requirements.txt
depthai_sdk/setup.py
depthai_sdk/src/depthai_sdk/managers/blob_manager.py
requirements.txt

User on discord reported [this problem](https://discord.com/channels/790680891252932659/924798783521439804/1067196573253107883); with new depthai 2.20 getting default openvino version fails, so blobconverter can't download models.
Current workaround: `python3 depthai_demo.py --openvinoVersion 2021_4`

[Hotfix] depthai demo openvino problem

---

test_ui.py

Fix for `test_ui.py` as it crashed out on FFC cameras now - `init()` returned early.

Create eepromUnionData on top

---

depthai_sdk/examples/StereoComponent/stereo.py
depthai_sdk/setup.py
depthai_sdk/src/depthai_sdk/components/stereo_component.py
depthai_sdk/src/depthai_sdk/oak_camera.py

Usage:
```python
import depthai as dai
stereo = oak.create_stereo('800p', fps=30, encode='h264')
stereo.set_colormap(dai.Colormap.STEREO_TURBO)
oak.visualize(stereo.out.encoded)
```

On-device stereo colorization

---

depthai_sdk/src/depthai_sdk/components/camera_component.py

DDR usage for pipeline below for prev. version of 180 deg rotation: 98_141_184/357_154_815 
DDR usage for pipeline below for updated version of 180 deg rotation: 73_254_912/357_154_815
```python
from depthai_sdk import OakCamera, CameraComponent
with OakCamera(rotation=180) as oak:
cam_component: CameraComponent = oak.create_camera(source="color", fps=10, resolution="1080p")
oak.visualize(cam_component)
```

Updated 180 deg rotation.

---

depthai_helpers/calibration_utils.py

In the current state we check if the cornerrs are detected before capturing the image. But some times the undistorted image is slightly cropped and the markers are no longer visible. This causes an error in the `test_epipolar_charuco` function when calling `cv2.aruco.interpolateCornersCharuco` we get this error:
```
Device closed in exception..
OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv_contrib\modules\aruco\src\charuco.cpp:448: error: (-215:Assertion failed) _markerCorners.total() == _markerIds.getMat().total() && _markerIds.getMat().total() > 0 in function 'cv::aruco::_interpolateCornersCharucoLocalHom'
File "C:\Users\user\depthai\calibrate.py", line 911, in calibrate
status, result_config = stereo_calib.calibrate(
File …
```

Check if markers were detected on undistorted image

---

depthai_helpers/calibration_utils.py

Trying to get the fisheye camera model working

Peripheral calibration - fisheye camera model

---

.gitmodules
depthai_sdk/examples/CameraComponent/preview_all_cameras.py
depthai_sdk/examples/mixed/switch_between_models.py
depthai_sdk/requirements.txt
depthai_sdk/src/depthai_sdk/components/camera_component.py
depthai_sdk/src/depthai_sdk/components/camera_helper.py
depthai_sdk/src/depthai_sdk/components/component.py
depthai_sdk/src/depthai_sdk/components/imu_component.py
depthai_sdk/src/depthai_sdk/components/nn_component.py
depthai_sdk/src/depthai_sdk/components/parser.py
depthai_sdk/src/depthai_sdk/components/stereo_component.py
depthai_sdk/src/depthai_sdk/oak_camera.py
depthai_sdk/src/depthai_sdk/oak_outputs/xout/xout_nn.py

- Refactored component creation, so we have device/pipeline on component creation already
- ^ allows getting available camera sensors on device and their resolutions. Now SDK supports OAK-D-LR / OAK-D-SR
- Added oak.create_all_cameras() function, creates List[CameraComponent] for each camera sensor on the OAK cam, example code below
- Added support so NNComponent accepts node output as an input

Refactored how pipeline is being built

---

depthai_sdk/examples/recording/encoder_preview.py
depthai_sdk/requirements.txt
depthai_sdk/src/depthai_sdk/classes/output_config.py
depthai_sdk/src/depthai_sdk/classes/packets.py
depthai_sdk/src/depthai_sdk/components/nn_component.py
depthai_sdk/src/depthai_sdk/oak_outputs/xout/xout_depth.py
depthai_sdk/src/depthai_sdk/oak_outputs/xout/xout_frames.py
depthai_sdk/src/depthai_sdk/oak_outputs/xout/xout_h26x.py
depthai_sdk/src/depthai_sdk/oak_outputs/xout/xout_mjpeg.py
depthai_sdk/src/depthai_sdk/oak_outputs/xout/xout_nn.py
requirements.txt

This returns dai.NNData objects:
```
color = oak.create_camera('color')
nn = oak.create_nn('yolov7tiny_coco_640x352', color)
oak.visualize([nn.out.main], fps=True)
def cb(packet):
print(packet.nn_data)
oak.callback(nn.out.nn_data, callback=cb)
```

Out network support

---

depthai_sdk/src/depthai_sdk/oak_camera.py
depthai_sdk/src/depthai_sdk/oak_device.py
depthai_sdk/src/depthai_sdk/oak_outputs/xout/xout_base.py
depthai_sdk/src/depthai_sdk/oak_outputs/xout/xout_frames.py

Inside `XoutFrames`, when called `__del__`, self._video_recorder was always None, so it didn't properly close the .mp4 video file and it was invalid (video players failed). I guess GC did its thing beforehand.
```
def __del__(self):
if self._video_recorder:
```
TODO: Fix recording both right + stereo, currently right isn't recorded:
```
left = oak.create_camera('left', resolution='800p')
right = oak.create_camera('right', resolution='800p')
stereo = oak.create_stereo(left=left, right=right)
oak.visualize(stereo.out.disparity, record_path='stereo.mp4')
oak.visualize(right, record_path='right.mp4')

Fix frame recording

---

depthai_sdk/examples/CameraComponent/camera_control.py
depthai_sdk/src/depthai_sdk/components/camera_component.py
depthai_sdk/src/depthai_sdk/components/camera_controls.py
depthai_sdk/src/depthai_sdk/components/component.py
depthai_sdk/src/depthai_sdk/oak_camera.py

```
color = oak.create_camera('color')
oak.visualize([color], fps=True, scale=2/3)
oak.start()
while oak.running():
key = oak.poll()
if key == ord('i'):
color.control.exposure_time_down()
elif key == ord('o'):
color.control.exposure_time_up()
elif key == ord('k'):
color.control.sensitivity_down()
elif key == ord('l'):
color.control.sensitivity_up()
elif key == ord('e'): # Switch to auto exposure
color.control.send_controls({'exposure': {'auto': True}})
```

Added runtime camera control feature

---

depthai_sdk/src/depthai_sdk/components/multi_stage_nn.py
depthai_sdk/src/depthai_sdk/components/nn_component.py
depthai_sdk/src/depthai_sdk/components/template_multi_stage_script.py

Previously only cropping was supported.
Now letterboxing/stretch work as well, examples below:
https://github.com/luxonis/depthai/assets/18037362/422f950e-98d1-4932-923f-3e483e4e32b9
https://github.com/luxonis/depthai/assets/18037362/bd943f74-1f09-4b81-a40c-0faea2b2a39d

Added support for 2stage NNs to use all resize modes for detection 

---

depthai_sdk/examples/CameraComponent/camera_control_with_nn.py
depthai_sdk/src/depthai_sdk/classes/output_config.py
depthai_sdk/src/depthai_sdk/components/camera_component.py
depthai_sdk/src/depthai_sdk/components/camera_helper.py
depthai_sdk/src/depthai_sdk/components/control_camera_with_nn.py
depthai_sdk/src/depthai_sdk/components/template_control_cam_with_nn.py

added option to control the camera component (auto-focus and auto-exposure) with nn detection results.
```
color = oak.create_camera('color')
face_det = oak.create_nn('face-detection-retail-0004', color)
color.control_with_nn(face_det, auto_focus=True, auto_exposure=True, debug=False)
oak.visualize(face_det, fps=True)
```
**Left**: default AF/AE. **Right**: AF/AE on detected face (code sample above)

Control camera with NN results

---

depthai_sdk/src/depthai_sdk/components/camera_component.py
depthai_sdk/src/depthai_sdk/components/stereo_component.py
depthai_sdk/src/depthai_sdk/oak_camera.py

- Reuse existing components in stereo creation
- Return existing `CameraComponent` when same socket is specified
- Pick first color sensor when source is `color` or `rgb` (OAK-D-SR support)
- Rename `create_camera` with just `camera` (same for `stereo` and `all_cameras`)

Reuse existing components

---

depthai_sdk/src/depthai_sdk/utils.py

It was previously crashing on WIndows, as it doesn't have `/tmp/` path

Fix crashdump report

---

depthai_sdk/examples/CameraComponent/preview_all_cameras.py
depthai_sdk/src/depthai_sdk/components/camera_component.py
depthai_sdk/src/depthai_sdk/components/camera_helper.py
depthai_sdk/src/depthai_sdk/components/nn_component.py
depthai_sdk/src/depthai_sdk/components/parser.py
depthai_sdk/src/depthai_sdk/components/pointcloud_component.py
depthai_sdk/src/depthai_sdk/components/stereo_component.py
depthai_sdk/src/depthai_sdk/oak_camera.py

A few fixes:
- When creating `color` camera, it will take first color sensor, which fixes many issues for eg. OAK-D-SR
- Auto-downscale stereo frames if they're above 1280pixels in width; fixes issues with OAK-D-LR
- Select stereoLeft camera when creating `left` camera, and stereoRight when creating `right` camera. This could fix some issues with custom devices, or FFC setups, where left/right aren't cam_b/cam_c ports
- In CameraComponent, added option for `resolution='max'`, whcih will set max supported camera resolution
TODO:
- When PR: https://github.com/luxonis/depthai-python/pull/862 gets to mainline, SDK can use `Camera` node instead of `ColorCamera`/`MonoCamera` nodes.

Support for non-standard devices

---

depthai_sdk/src/depthai_sdk/components/camera_component.py
depthai_sdk/src/depthai_sdk/components/camera_helper.py

- H26x encoder needs height to be divisible by 8
- Replaced while loops with division

Fix getClosestVideoSize for encoder input

---

depthai_sdk/examples/IMUComponent/imu.py

Tiny PR to fix the call to oak.visualize() is [depthai_sdk/examples/IMUComponent/imu.py#L8](https://github.com/luxonis/depthai/blob/5fb3c41652e20652047dc632221d591d9e8087e7/depthai_sdk/examples/IMUComponent/imu.py#L8) which was producing this error:
```shell
$ python depthai_sdk/examples/IMUComponent/imu.py
Closing OAK camera
File "/Users/arnlen/depthai/depthai_sdk/examples/IMUComponent/imu.py", line 8, in <module>
oak.visualize(imu.out.main, visualizer='viewer')
TypeError: OakCamera.visualize() got an unexpected keyword argument 'visualizer'
```
Removing the arg `visualizer='viewer'` fixed it. ✅

Fix depthai_sdk/examples/IMUComponent/imu.py: remove wrong arg in oak.visualize() call

---

depthai_sdk/src/depthai_sdk/oak_camera.py

Having a queue bigger than one in case only callbacks are used is only "wasting" memory, since no one ever uses the messages in the queue.

Change queue size to 1

---

depthai_sdk/src/depthai_sdk/integrations/roboflow.py

Moving the requests.get(url) below the check for the cache.  If your vision system is offline, and you have a cached model, the call to requests prior to checking the cache throws an exception.  Now if you have a cached model it will use that first and only if you do not have a model will it switch to checking api.roboflow.com

Allow use of prior cached model

---

calibrate.py

Added ability to manually specify sensor model inside the .json config file. 
If camera has `model` entry, it will manually set the name as well as type supported, otherwise the script will function as before. 
This is useful on modular OAK designs when sensors (namely OV9782 and OV9282) aren't correctly recognized.

Updated calibrate.py

---

depthai_sdk/src/depthai_sdk/trigger_action/trigger_action.py

Line 40 in trigger_action.py appeared to have an old import reference to logging so I updated it to match new import of LOGGER.

Fixed a fatal bug on the trigger_action.py

---

.github/workflows/demo.workflow.yml
depthai_sdk/examples/recording/multidevice_rgbd_record.py

Records (synced) multi-device RGB-D streams (rgb mjpeg .mp4 container, depth on-host encoded ffv1 .avi container).

Added multideice rgbd record example inside SDK
